# action.yml
name: 'Dbmate action'
branding:
  icon: 'archive'
  color: 'gray-dark'
description: 'Run Dbmate database migration tool'
inputs:
  command:
    description: 'Dbmate command to run'
    required: false
    default: '--help'
  dbmate_version:
    description: 'Dbmate version to use'
    required: false
    default: 'latest'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/amacneil/dbmate:${{ inputs.dbmate_version }}'
  args:
    - ${{ inputs.command }}
