# action.yml
name: 'Dbmate action'
branding:
  icon: 'archive'
  color: 'gray-dark'
description: 'Run Dbmate database migration tool'
inputs:
  command:
    description: 'Dbmate command to run'
    required: false
    default: '--help'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/amacneil/dbmate:1.15'
  args:
    - ${{ inputs.command }}
